// Generated by https://quicktype.io

export interface IGuia {
    apellidos: string;
    nombre: string;
    id: string;
    telefono: string;
    zona: string;
}

export interface IGuiaRequest {
    apellidos: string;
    nombre: string;
    telefono: string;
    zona: string;
}
